---

- name: copy maintenance nginx.conf
  copy:
    src: "{{ worker_home }}/nginx/conf/nginx.conf"
    dest: "{{ worker_home }}/nginx/conf/nginx.conf.maintenance"
    remote_src: yes
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"

- name: Recovery normal nginx.conf
  copy:
    src: "{{ worker_home }}/nginx/conf/nginx.conf.normal"
    dest: "{{ worker_home }}/nginx/conf/nginx.conf"
    remote_src: yes
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"

- name: 测试配置文件
  shell: "{{ worker_home }}/nginx/sbin/nginx -t"
  register: nginx_test
  ignore_errors: true

- debug:
    msg: "{{nginx_test.stderr_lines}}"

- name: 启动 nginx
  shell: "{{ worker_home }}/nginx/sbin/nginx -s reload"
  ignore_errors: true

- name: 检查nginx进程
  shell: ps -ef | grep -v grep | grep nginx
  register: nginx_process
  ignore_errors: true

- debug:
    msg: "{{ nginx_process.stdout_lines }}"
  ignore_errors: true

- debug:
    msg: "别忘了检查网站是否能正常访问"
  ignore_errors: true