# 请提供 org 变量（需刷新 Keylist 的组织名称）
---
- name: 刷新 Keylist
  hosts: "peer0.{{ org | default('org1') }}"
  tasks:
  - include_vars:
      file: vars/chaincode.yml

  - include_role:
      name: fabric_cli
    vars:
      operation: keylist
      channel: "{{ item }}"
      chaincode_list: "{{ fabric_channels[item]['chaincodes'] }}"
    loop: "{{ join_channels }}"
