# deploy JDK
# Use the -e input variable, eg：inventory=org1_java
---

- name: deploy JDK
  hosts: "{{ inventory | default('*_unique') }}"
  gather_facts: false
  vars_files:
    - 1_vars/common.yml
  roles:
    - role: jdk
