# Use the -e input variable, eg："inventory=org11_hbcc"
---

- name: supervisor
  hosts: "{{ inventory }}"
  gather_facts: false
  vars_files:
    - 1_vars/common.yml
  tasks:
  - import_role:
      name: supervisor
    vars:
      operation: install
