---
# 融联环境参数: -e "inventory=zookeeper:kafka:org1_orderer:org1_peer:org11_orderer:org11_peer:org12_orderer:org12_peer"
# 阿里生产参数: -e "inventory=org19_peer"

- name: backup
  hosts: zookeeper:kafka:ord1_orderer:org1_peer:ord12_orderer:org12_peer
  vars:
    #time: "{{ansible_date_time.iso8601_basic_short}}"
    time: "{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}T{{ansible_date_time.hour}}"
    back_dir: "/data/autobackup/{{ time }}"
    #worker_group: blockchain
    #worker_user: blockchain
  tasks:
  - find:
      paths: "{{ back_destination_path | default('/data/autobackup') }}"
      age: 7d
      file_type: directory
    register: expired_dirs

  - file:
      path: "{{ item }}"
      state: absent
    with_items: "{{ expired_dirs.files.path }}"

  - name: 创建工作目录
    file:
      path: "{{ back_dir }}"
      state: directory
      group: "{{ worker_group }}"
      owner: "{{ worker_user }}"

  - name: archive tar.gz
    archive:
      path: "{{ fabric_data }}"
      dest: "{{ back_dir }}/{{ inventory_hostname }}.tgz"
      group: "{{ worker_group }}"
      owner: "{{ worker_user }}"