---

- name: 载入变量
  include_vars: "../../../vars/{{ item }}.yml"
  with_items:
    - var
    - dns
    - hosts

- name: 创建 fft 工作目录
  file:
    path: "{{ worker_home }}/forfaiting_portal"
    state: directory
    group: "{{ worker_user }}"
    owner: "{{ worker_user }}"

- name: 安装 fft java
  unarchive:
    src: forfaiting-service-ws-1.1.7.tar.gz
    dest: "{{ worker_home }}/forfaiting_portal"
    group: "{{ worker_user }}"
    owner: "{{ worker_user }}"

- name: 确保原配置文件干净
  file:
    path: "{{ fft_dir }}/{ item }}"
    state: absent
  with_items:
    - config/application_custom.properties
    - bin/fft.sh

- name: 上传配置文件和启动脚本
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ fft_dir }}/{{ item.dest }}"
    group: "{{ worker_user }}"
    owner: "{{ worker_user }}"
  with_items:
    - { src: application_custom.properties, dest: config/application_custom.properties }
    - { src: fft.sh, dest: bin/fft.sh }

- name: 确保工作目录属主
  file:
    path: "{{ fft_dir }}"
    owner: "{{ worker_user }}"
    group: "{{ worker_group }}"
    recurse: yes
    state: directory