---
# handlers file for beats

- name: restart the service
  become: yes
  service:
    name: "{{ beat }}"
    state: restarted
    enabled: true
  when: start_service and restart_on_change and not beats_started.changed
