---

mongo_replic_hosts:
  - "{{ hostvars['mongodb-p'].ansible_ssh_host }} mongodb1.{{ app_domain }}"
  - "{{ hostvars['mongodb-s'].ansible_ssh_host }} mongodb2.{{ app_domain }}"
  - "{{ hostvars['mongodb-a'].ansible_ssh_host }} mongodb3.{{ app_domain }}"