---

- name: 上传 jdk 安装包
  copy:
    src: summary_files/jdk/jdk-{{ java_major_version }}u{{ java_update_version }}-linux-x64.rpm
    dest: "{{ summary_dir }}/tools"
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"

- name: 安装 jdk
  yum:
    name: "{{ summary_dir }}/tools/jdk-{{ java_major_version }}u{{ java_update_version }}-linux-x64.rpm"
    state: present

- name: 设置 JAVA_HOME 全局环境变量
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
  with_items:
    - '# java 环境变量'
    - 'export JAVA_HOME=/usr/java/jdk1.{{ java_major_version }}.0_{{ java_update_version }}'
    - 'export JRE_HOME=${JAVA_HOME}/jre'
    - 'export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib'
    - 'export PATH=${JAVA_HOME}/bin:$PATH'
