---

- name: 创建工作目录
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"
  with_items:
    - "{{ ccname_home }}/{{ ccname | default ('fft') }}api"
    - "{{ ccname_home }}/{{ ccname | default ('fft') }}event"
    - "{{ worker_home }}/images"
    - "{{ fabric_home }}/crypto-config/ordererOrganizations"
    - "{{ fabric_home }}/crypto-config/peerOrganizations"

- name: 上传镜像
  copy:
    src: "../../../summary_files/docker-images/{{ fabric_deploy_ver | default('1.0') }}/{{ item }}"
    dest: "{{ worker_home }}/images/"
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"
  with_items:
    - apiserver.tar
    - eventserver.tar
  when: not harbor
  
- name: 镜像导入docker
  shell: docker load -i {{ worker_home }}/images/{{ item }}
  args:
    chdir: "{{ worker_home }}/images"
  with_items:
    - apiserver.tar
    - eventserver.tar
  when: not harbor
  
- name: pull 镜像
  become: yes
  become_user: "{{ worker_user }}"
  command: docker pull {{ harbor_domain | default ('hub.finrunchain.com') }}/{{ harbor_project }}/{{ item }}:latest
  with_items:
    - apiserver
    - eventserver
  when: harbor

- name: 上传 fabric 证书
  copy:
    src: "{{ playbook_dir }}/{{ inventory_file | basename }}/crypto-config/{{ item.src }}"
    dest: "{{ fabric_home }}/crypto-config/{{ item.dest }}"
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"
  with_items:
    - { src: 'ordererOrganizations/ord{{org_id}}.{{ fabric_domain }}' , dest: 'ordererOrganizations' }
    - { src: 'peerOrganizations/org{{org_id}}.{{ fabric_domain }}' , dest: 'peerOrganizations' }

- name: 生成 current.info
  file:
    path: "{{ ccname_home }}/{{ ccname | default ('fft') }}event/current.info"
    state: touch
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"
    mode: "u=rw,g=rw,o=r"
  when: ccname != "ctfu"

- name: 上传 Event 配置模板
  template:
    src: "{{ item.src }}"
    dest: "{{ ccname_home }}/{{ ccname | default ('fft') }}event/{{ item.dest }}"
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"
    backup: yes
  with_items:
    - { src: 'event_client_sdk.j2' , dest: 'client_sdk.yaml' }
    - { src: 'event.j2' , dest: 'docker-compose.yml' }

- name: 上传 API 配置模板
  template: 
    src: "{{ item.src }}"
    dest: "{{ ccname_home }}/{{ ccname | default ('fft') }}api/{{ item.dest }}"
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"
    backup: yes
  with_items:
    - { src: 'api_client_sdk.j2' , dest: 'client_sdk.yaml' }
    - { src: 'api.j2' , dest: 'docker-compose.yml' }

- name: 启动 docker 容器
  become: yes                
  become_user: "{{ worker_user }}"
  command: /usr/local/bin/docker-compose -f {{ ccname_home }}/{{ ccname | default ('fft') }}{{ item }}/docker-compose.yml up -d
  with_items:
    - api
    - event
  tags:
    - rebuild

- name: 等待10秒
  wait_for:
    timeout: 10
  tags: rebuild

- name: 检查容器启动是否正常
  shell: docker ps -a -f name={{ ccname | default ('fft') }}
  register: docker_status
  tags:
    - rebuild
- debug:
    msg: "{{ docker_status.stdout_lines }}"
  tags:
    - rebuild

- name: 检查 API 容器的id
  shell: docker ps -aq -f name=apiserver_{{ ccname | default ('fft') }}
  register: api_containers
  tags:
    - rebuild
#- debug:
#    msg: "{{ api_containers.stdout_lines }}"

- name: 获得完整的 API 容器的id
  shell: ls /var/lib/docker/containers/ | grep {{ api_containers.stdout }}
  register: api_containers_nu
  tags:
    - rebuild
- debug:
    msg: "{{ api_containers_nu.stdout }}"
  tags:
    - rebuild

- name: 等待 API port 监听
  wait_for:
    port: "{{ api_port }}"
    delay: 10
  tags:
    - rebuild

- name: 检查 API 启动是否正常
  shell: "grep 'CRIT : Actual pid is' /var/lib/docker/containers/{{ api_containers_nu.stdout }}/{{ api_containers_nu.stdout }}-json.log"
  register: api_status
  tags:
    - rebuild
- debug:
    msg: "{{ api_status.stdout_lines }}"
  tags:
    - rebuild

- name: 底层探活
  shell: curl -I http://127.0.0.1:{{ api_port }}/factor/keepaliveQuery
  register: fabric_status
  tags:
    - rebuild
- debug:
    msg: "{{ fabric_status.stdout_lines }}"
  tags:
    - rebuild

- name: 创建bin目录
  file:
    path: "{{ fabric_home }}/bin"
    state: directory
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"

- name: 底层探活验证脚本
  template:
    src: "{{ item }}.j2"
    dest: "{{ fabric_home }}/bin/{{ ccname|default('fft') }}-{{ item }}"
    group: "{{ worker_group }}"
    owner: "{{ worker_user }}"
    mode: 0755
  with_items:
    - live.sh
    - savedata.sh
  tags: test  
