---
# Connection
ansible_ssh_user: root
ansible_ssh_private_key_file: "{{ playbook_dir }}/0_inventory/inventory-Hoke/sshkey/id_rsa"
ansible_ssh_pass: "Welc@me1"

# System
worker_group: blockchain
worker_gid: 1500
worker_user: blockchain
worker_uid: 1500
worker_home: "/home/{{ worker_user }}"

# Fabric Orderer & Genesis
fabric_orderer_type: etcdraft
fabric_genesis_orgs:
  ords:
  - ord1
  orgs:
  - org1


# Fabric channels and chaincodes
fabric_channels:
  channelsupplychain:
    orgs:
    - org1
    - org2
    chaincodes:
    - name: supplychain
      getKeys: True
      version: 1.1.3
#    - name: haiyun
#      version: 0.1.1
    api:
      listen_port: 5555
      domain: apiserver.{{ org_domain }}
      channel: channelsupplychain
      chaincode: supplychain
#      chaincode: haiyun
      rabbitmq_exchange: supplychainExchange
      rabbitmq_group: rabbitmq

rsa_pri_0: |
  -----BEGIN PRIVATE KEY-----
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCoU4KRxLFTIlZ
  EWqVEBPvVptgysMIIUJZyHcx9jjz1srZSxN7dCMWgo6BukD1yS1LEVqQ0Tf7ksY3
  fDQ9hUIoUykT1coi8HXIJiLFUX4kb6s0nW4xPCHKxIBIlqWqEGnn14JPsSIo8HWM
  ev1lmVlCFh4iMnyh8Pl+iaJlb91sEEjvOy52ezcEElgEXa0AGqOHYl0t5d1QWAW3
  x+5qqxnFUM0Uxj0aqEg/UjktT4whKNko6gv6XMaV0Uaa8vLCXBwx8bPpqaEMur5O
  BgfHuEoj2u6fmsS/caS29ldKbUlLZA0jILsIpIja+3G5alNrz2f3tFHwiAUClSOo
  C9bskPlJAgMBAAECggEASyr/N+rxLe/8T8DxN/bIrDP3uG822cn2lTReDJa6sjnv
  h/J96L0W3Be6MBIeCo8TBh4Cq1GSXH/4O++lQWlY/rf3cmisM8hIxO8tmKV7oVjb
  d2uh5jQCHQy9Osur2b2TGW5bLqoLtmIAFCxf90A9f8+I/c4f4m9t/Fftt11318bZ
  p/pObc6FjOfG32ITxHeC1zUTdBlAJAt7XWF+VpYF9G4lR73uSBKMHcpt3oPTSyF0
  A5f/0hsiVdzxiF6EQnji/FG4kKmGtEmhfcT9fBTsi8nnxvtx1ofEKQ1qgPTlOeDI
  jJJ50PQkDxdCJdOeFFHh38FaOw8VUVVI9fj7zro+AQKBgQDrrDemygWlU3zWhQwb
  L5CP8eSRASSVEteOSTaB5NuxR+tAfwImlckvopW/I/30j6Y+9ahKgsSmk82TZjdE
  SWQZ+31XY2TOZ0qe22/CUebivH5WhRHTA5u5/GfP81wRaXInaItYG6phHKjCXDbz
  U/htu8T07XcOWvRJOdy1PulYQQKBgQDTatgDwNb+0UUMv2w9OWZ94HA1IL4LERL0
  x0AoyYf0xNecFMHpxhwSl0ThRbvag7y6IVWbDW0YR9mcZTW7q/FZUF66dgt2LJci
  rhqkpOAIZOEQX1wUYANSlT1d6zSi5JWpb0NTf0oRN4IEV7DaUtik9Hx0znWQwA7f
  UB1+oW0fCQKBgQCAELSpKOzKe0TCWchLWZyH7B2VgnZ7n6KNClHZYiDUBE3dXWcw
  yoJqJUKUfJ168TiYy+tomgj8sCKtL4Vm0S7ZQ6VIAJX953lQO9ROVy1NFrrcjzEx
  ZquP9I4BHbBxMci7i371IQuD/AvkmjGuJnpAPyH3KrdgkKJgzFWYFBi/QQKBgQCn
  bOl8r26Tha6lFcLmCVr9PIwfxro5kV/tsQ1CP7cHRAtrc5TNSTJaFqlZrRvDRKhk
  zpk4nT1UCTJwBEa1RMlw7ZDXITyabV2S/UXkNR2mCB2kFaCaEh8Pe1iJ1AZvKY7M
  C2zJ5vgFAmxYfAl2HD2tBGC7L/UymKYuewegjL4Z4QKBgFRAF7tEFd2sHw/Co435
  m/wPxk11HaOoz1NVd69ouZxWqB5w+j9RjpPdHvmEII++rW6WlTvbmruNRaamduiU
  ODmVJg5eHeXPIioflaoR4qT7L266P9aw+nEAOwPBA/zMw1uOb+KFOn6pE5RdlPGO
  fojPugzB+d/mcRKl8jIpAXYq
  -----END PRIVATE KEY-----
rsa_pub_0: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwqFOCkcSxUyJWRFqlRAT
  71abYMrDCCFCWch3MfY489bK2UsTe3QjFoKOgbpA9cktSxFakNE3+5LGN3w0PYVC
  KFMpE9XKIvB1yCYixVF+JG+rNJ1uMTwhysSASJalqhBp59eCT7EiKPB1jHr9ZZlZ
  QhYeIjJ8ofD5fomiZW/dbBBI7zsudns3BBJYBF2tABqjh2JdLeXdUFgFt8fuaqsZ
  xVDNFMY9GqhIP1I5LU+MISjZKOoL+lzGldFGmvLywlwcMfGz6amhDLq+TgYHx7hK
  I9run5rEv3GktvZXSm1JS2QNIyC7CKSI2vtxuWpTa89n97RR8IgFApUjqAvW7JD5
  SQIDAQAB
  -----END PUBLIC KEY-----

