---
# Connection
ansible_ssh_user: root
ansible_ssh_private_key_file: "{{ playbook_dir }}/summary_files/common/sshkey/id_rsa_1024_root"
#ansible_ssh_pass: runchain_2018
ansible_ssh_common_args: '-o ConnectTimeout=60s'


inventory_dir_basename: "{{ inventory_dir | basename }}"
# Environment Type, such as: demo, test, sit, prod ...
env_type: "{{ inventory_dir_basename.split('-')[1] | lower }}"
# Ansible local file directory
env_src: "environment/{{ inventory_dir_basename }}"

# System
worker_group: blockchain
worker_gid: 1500
worker_user: blockchain
worker_uid: 1500
worker_home: "/home/{{ worker_user }}"
summary_dir: "{{ worker_home }}/summary"
yum: true
sysctl:
  - description: 最大使用物理内存，默认值60
    name: vm.swappiness
    value: '10'
  - name: net.ipv4.ip_forward
    value: '1'
  - name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '1'
  - name: net.ipv4.icmp_ignore_bogus_error_responses
    value: '1'
  - name: net.ipv4.neigh.default.gc_stale_time
    value: '120'
  - name: net.ipv4.conf.all.rp_filter
    value: '0'
  - name: net.ipv4.conf.default.rp_filter
    value: '0'
  - name: net.ipv4.conf.default.arp_announce
    value: '2'
  - name: net.ipv4.conf.all.arp_announce
    value: '2'
  - name: net.ipv4.conf.lo.arp_announce
    value: '2'
  - name: net.ipv4.tcp_max_tw_buckets
    value: '5000'
  - name: net.ipv4.tcp_tw_reuse
    value: '1'
  - name: net.ipv4.tcp_fin_timeout 
    value: '30'
  - name: net.ipv4.tcp_syncookies
    value: '1'
  - name: net.ipv4.tcp_max_syn_backlog
    value: '8192'
  - name: net.ipv4.tcp_synack_retries
    value: '2'
  - name: net.ipv4.tcp_keepalive_time
    value: '600'
  - name: net.ipv6.conf.all.disable_ipv6
    value: '1'
  - name: net.ipv6.conf.default.disable_ipv6
    value: '1'
  - name: net.ipv6.conf.lo.disable_ipv6
    value: '1'
  - name: vm.max_map_count
    value: '262144'
  - name: net.core.somaxconn
    value: '4096'

# Docker
docker_version: 17.06.1.ce-1.el7.centos
harbor: true
harbor_domain: hub.finrunchain.com
harbor_user: ansible
harbor_passwd: Ansible123

# Fabric common
fabric_deploy_ver: 1.4.0
fabric_thirdparty_version: amd64-0.4.15
fabric_domain: finblockchain.cn

fabric_minor_ver: "{{ fabric_deploy_ver.split('.')[1] }}"
fabric_home: "{{ worker_home }}/{{ inventory_hostname }}"
fabric_data: "/data/{{ inventory_hostname }}"

# Fabric channels and chaincodes
fabric_channels:
  channelyonyoubucket:
    -
      name: yonyoubucket
      version: 0.1.2

# Kafka
kafka_domain: finblockchain.cn

# Network - 定义机构之间使用私网（private）还是公网（public）连接
# private: Peer --> Orderer --> Kafka 均通过私网连接；（账本3.0）Platform 之间通过私网连接
conn_mode: private
# public: 无 Orderer 的入盟机构，Peer --> Orderer 通过公网；有 Orderer 的入盟机构，Peer --> Orderer 仍是私网，但 Orderer --> Kafka 通过公网
#conn_mode: public

# JDK
java_major_version: 8
java_update_version: 91

# Platform (ledger3.0 only)
platform:
- id: pid001
  name: pid001
  description: DF Platform Runtime
  scheme: http
  host: platform.org1.{{ fabric_domain }}
  port: 4001
  fabric_id: org1
- id: pid002
  name: pid002
  description: Voucher Platform Runtime
  scheme: http
  host: platform.org1.{{ fabric_domain }}
  port: 4000
  fabric_id: org1
- id: pid003
  name: pid003
  description: RDF Platform Runtime
  scheme: http
  host: platform.org1.{{ fabric_domain }}
  port: 4002
  fabric_id: org1

# RSA key pair (ledger 3.0 only)
rsa_pri_0: |
  -----BEGIN PRIVATE KEY-----
  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCoU4KRxLFTIlZ
  EWqVEBPvVptgysMIIUJZyHcx9jjz1srZSxN7dCMWgo6BukD1yS1LEVqQ0Tf7ksY3
  fDQ9hUIoUykT1coi8HXIJiLFUX4kb6s0nW4xPCHKxIBIlqWqEGnn14JPsSIo8HWM
  ev1lmVlCFh4iMnyh8Pl+iaJlb91sEEjvOy52ezcEElgEXa0AGqOHYl0t5d1QWAW3
  x+5qqxnFUM0Uxj0aqEg/UjktT4whKNko6gv6XMaV0Uaa8vLCXBwx8bPpqaEMur5O
  BgfHuEoj2u6fmsS/caS29ldKbUlLZA0jILsIpIja+3G5alNrz2f3tFHwiAUClSOo
  C9bskPlJAgMBAAECggEASyr/N+rxLe/8T8DxN/bIrDP3uG822cn2lTReDJa6sjnv
  h/J96L0W3Be6MBIeCo8TBh4Cq1GSXH/4O++lQWlY/rf3cmisM8hIxO8tmKV7oVjb
  d2uh5jQCHQy9Osur2b2TGW5bLqoLtmIAFCxf90A9f8+I/c4f4m9t/Fftt11318bZ
  p/pObc6FjOfG32ITxHeC1zUTdBlAJAt7XWF+VpYF9G4lR73uSBKMHcpt3oPTSyF0
  A5f/0hsiVdzxiF6EQnji/FG4kKmGtEmhfcT9fBTsi8nnxvtx1ofEKQ1qgPTlOeDI
  jJJ50PQkDxdCJdOeFFHh38FaOw8VUVVI9fj7zro+AQKBgQDrrDemygWlU3zWhQwb
  L5CP8eSRASSVEteOSTaB5NuxR+tAfwImlckvopW/I/30j6Y+9ahKgsSmk82TZjdE
  SWQZ+31XY2TOZ0qe22/CUebivH5WhRHTA5u5/GfP81wRaXInaItYG6phHKjCXDbz
  U/htu8T07XcOWvRJOdy1PulYQQKBgQDTatgDwNb+0UUMv2w9OWZ94HA1IL4LERL0
  x0AoyYf0xNecFMHpxhwSl0ThRbvag7y6IVWbDW0YR9mcZTW7q/FZUF66dgt2LJci
  rhqkpOAIZOEQX1wUYANSlT1d6zSi5JWpb0NTf0oRN4IEV7DaUtik9Hx0znWQwA7f
  UB1+oW0fCQKBgQCAELSpKOzKe0TCWchLWZyH7B2VgnZ7n6KNClHZYiDUBE3dXWcw
  yoJqJUKUfJ168TiYy+tomgj8sCKtL4Vm0S7ZQ6VIAJX953lQO9ROVy1NFrrcjzEx
  ZquP9I4BHbBxMci7i371IQuD/AvkmjGuJnpAPyH3KrdgkKJgzFWYFBi/QQKBgQCn
  bOl8r26Tha6lFcLmCVr9PIwfxro5kV/tsQ1CP7cHRAtrc5TNSTJaFqlZrRvDRKhk
  zpk4nT1UCTJwBEa1RMlw7ZDXITyabV2S/UXkNR2mCB2kFaCaEh8Pe1iJ1AZvKY7M
  C2zJ5vgFAmxYfAl2HD2tBGC7L/UymKYuewegjL4Z4QKBgFRAF7tEFd2sHw/Co435
  m/wPxk11HaOoz1NVd69ouZxWqB5w+j9RjpPdHvmEII++rW6WlTvbmruNRaamduiU
  ODmVJg5eHeXPIioflaoR4qT7L266P9aw+nEAOwPBA/zMw1uOb+KFOn6pE5RdlPGO
  fojPugzB+d/mcRKl8jIpAXYq
  -----END PRIVATE KEY-----
rsa_pub_0: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwqFOCkcSxUyJWRFqlRAT
  71abYMrDCCFCWch3MfY489bK2UsTe3QjFoKOgbpA9cktSxFakNE3+5LGN3w0PYVC
  KFMpE9XKIvB1yCYixVF+JG+rNJ1uMTwhysSASJalqhBp59eCT7EiKPB1jHr9ZZlZ
  QhYeIjJ8ofD5fomiZW/dbBBI7zsudns3BBJYBF2tABqjh2JdLeXdUFgFt8fuaqsZ
  xVDNFMY9GqhIP1I5LU+MISjZKOoL+lzGldFGmvLywlwcMfGz6amhDLq+TgYHx7hK
  I9run5rEv3GktvZXSm1JS2QNIyC7CKSI2vtxuWpTa89n97RR8IgFApUjqAvW7JD5
  SQIDAQAB
  -----END PUBLIC KEY-----
