version: '2'
services:
  fabric-ca-server:
    image: registry.hoperun.com/hyperledger/fabric-ca:amd64-1.4.2
    container_name: fabric-ca
    ports:
      - "7054:7054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - "./fabric-ca-server:/etc/hyperledger/fabric-ca-server"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
